### ISSUE TITLE
Do we need `IOTimedMatchers`?

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2-cats#16]
Came up in https://github.com/etorreborre/specs2-cats/pull/13#issuecomment-945419312. While I personally would never use it, I'm fine to keep it. But I do think the name is confusing. Like something that would do #7 rather than be synchronous/blocking.

**Comment by etorreborre** [comment]
I propose the following:

 - remove `IOTimedMatchers` in `specs2-cats`
 - deprecate `RunTimedMatchers` in `specs2` and document the non-blocking alternatives

**Comment by armanbilge** [comment]
That sounds great 😁
