### ISSUE TITLE
Add first-class support for ScalaCheck Effect

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2-cats#2]
https://github.com/typelevel/scalacheck-effect

**Comment by etorreborre** [comment]
This is not a small thing. ScalaCheck is quite strongly embedded into specs2 to be able to do two things:

 1. easily adjust the settings of properties, so there's a `prop` in `specs2` which encapsulates `forAll`:

```scala
class ScalaCheckSpec extends mutable.Specification with ScalaCheck:
  "this is a specific property" >> prop { (a: Int, b: Int) =>
    (a + b) == (b + a)
  }.set(minTestsOk = 200, workers = 3) // use "display" instead of "set" for additional console printing
```

2. use specs2 matchers inside ScalaCheck properties:
```scala
class ScalaCheckSpec extends mutable.Specification with ScalaCheck:
  "this is a specific property" >> prop { (a: Int, b: Int) =>
    (a + b) must ===(b + a)
  }
```

That doesn't seem out of reach, we need to probably mimic `forAllF` and provide a `propF` method with all the overloads to accept from 1 to 8 parameters.

**Comment by armanbilge** [comment]
Thanks, that's very informative, but I'll have to look into this more before I can completely wrap my head around it. What I'm confused about is whether `scalacheck-effect` is actually needed as a dependency, or it seems like `specs2-scalacheck-effect` can provide the same functionality without it?

**Comment by etorreborre** [comment]
I think we still need to use `scalacheck-effect` because it basically generalize the `scalacheck` internals to an `F[_]`. Maybe a better move would have been to generalize `ScalaCheck` to an `F` and write `forAll = forAllF[Either[Throwable, *]]`.

**Comment by armanbilge** [comment]
Oh, also I hope this `propF` / `forAllF`machinery still all works with `discipline-specs2` 🤔

**Comment by armanbilge** [comment]
This is the last one I want to tackle before we hopefully publish a pre-release! I'd like to start using this stuff in some of my proects :)
