### ISSUE TITLE
Setup release infrastructure

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2-cats#33]
After https://github.com/etorreborre/specs2-cats/pull/31 merges, I'd love to get a release so I can start to use this in my projects!

- I see this repo is already setup for CI release, are keys already installed?
https://github.com/etorreborre/specs2-cats/blob/4721ea22b82718db2c1bb545e5b9dde73805190b/.github/workflows/ci.yml#L58-L61
- Versioning: since this is published against specs2 v5 which is still in the RC stage and hasn't locked down binary-compatibility, it's more important to keep these projects in sync, and know which version of specs2-cats is compatible with which RC of specs2 itself.

Thanks :)

**Comment by etorreborre** [comment]
I will try to have a look at this  during the week

**Comment by armanbilge** [comment]
I noticed there were a couple existing tags, so I decided to give this a try—I hope you don't mind. It took a couple tries but I was able to publish [`SPECS2-CATS-1.0.0-ALPHA-04`](https://github.com/etorreborre/specs2-cats/releases/tag/SPECS2-CATS-1.0.0-ALPHA-04) :)

https://repo1.maven.org/maven2/org/specs2/specs2-cats_3/1.0.0-ALPHA-04/
https://repo1.maven.org/maven2/org/specs2/specs2-cats-effect_3/1.0.0-ALPHA-04/
https://repo1.maven.org/maven2/org/specs2/specs2-scalacheck-effect_3/1.0.0-ALPHA-04/

**Comment by symbiont-eric-torreborre** [comment]
Sorry I didn't get to do it eventually. I also had to fix an execution bug on specs2 and took the opportunity to use `targetName` thanks to one of your commits. 

I am now going to publish, put back the Mima check and finalize `5.0.0` if everything works ok

**Comment by etorreborre** [comment]
Sorry I didn't get to do it eventually. I also had to fix an execution bug on specs2 and took the opportunity to use `targetName` thanks to one of your commits.

I am now going to publish, put back the Mima check and finalize `5.0.0` if everything works ok

**Comment by armanbilge** [comment]
Sounds great!! Congratulations 😁  🤞
