### ISSUE TITLE
Matchers based on `cats.Eq` and `cats.Order`

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2-cats#45]
E.g. when comparing equality I often would like to use the `Eq` instance that I've defined for that type.

**Comment by gwils** [comment]
This would really help my project as well.

**Comment by armanbilge** [comment]
Unfortunately I haven't had a chance to work on this, but a PR would be fantastic!! :)

**Comment by etorreborre** [comment]
I just created a PR to get the ball rolling: https://github.com/etorreborre/specs2-cats/pull/91.

This should help with equality matchers but what about `cats.Order` instances. In which specs2 matcher should it be used? The only case I can think of is the matcher testing if a collection is sorted. Do you see anything else?

**Comment by armanbilge** [comment]
Wow, thank you!! 😁 

I was thinking these matchers.

![Screen Shot 2022-05-23 at 8 39 34](https://user-images.githubusercontent.com/3119428/169856466-cc4373a5-d82d-45a4-a081-8b9e0bba3d25.png)

**Comment by etorreborre** [comment]
Doesn't something like `beLessThanOrEqualTo` work using [this conversion](https://github.com/typelevel/cats/blob/main/kernel/src/main/scala/cats/kernel/Order.scala#L144)?

**Comment by armanbilge** [comment]
Ah, right, that _should_ work. I actually didn't know about that implicit for some reason 🤔

So then, if specs2 changes all its matchers to use `Ordering` then we don't need to do anything special in specs2-cats?

**Comment by symbiont-eric-torreborre** [comment]
All the ones you listed are using an `Ordering` instance so we should be covered, yes.

**Comment by etorreborre** [comment]
All the ones you listed are using an Ordering instance so we should be covered, yes.

**Comment by armanbilge** [comment]
I reckon we can close this as done by https://github.com/etorreborre/specs2-cats/pull/91 :)
