### ISSUE TITLE
Integrate CE `Resource` with specs2 `Resource`

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2-cats#6]
https://github.com/typelevel/cats-effect-testing/pull/203#issuecomment-915826715

**Comment by etorreborre** [comment]
Good point. I've [changed the mutable map into a concurrent one](ae7745d1ceda57023784ab77f678158f10bd18d8) to avoid any concurrency issues.

**Comment by armanbilge** [comment]
Thanks for the fix! But, I'm afraid that's not quite sufficient, I think there's still an atomicity issue for global resources. An example:
1. Thread A looks for global resource with key `K`. It gets `None`.
2. Thread B looks for global resource with key `K`. It gets `None`.
3. Thread A acquires the resource and stores its finalizer in the map under key `K`.
4. Thread B acquires the resource and stores its finalizer in the map under key `K`, replacing the one acquired by Thread A.

In this scenario, not only has the resource been acquired twice, but we've lost the finalizer for the first one and thus are leaking it.
