### ISSUE TITLE
Nested blocks are ignored

### ISSUE THREAD

**Issue by unthingable** [etorreborre/specs2-cats#98]
It appears that specs2 blocks nested within resource-enriched blocks are being ignored.

In the abbreviated snippet below, the test happily passes.

(Scala 3.1.1)
```scala
    val specs2           = "5.0.0"
    val specs2cats       = "1.0.0-ALPHA-07"
...
import cats.data.EitherT
import cats.effect.{Clock, IO, Resource}
import cats.syntax.all.given
import org.specs2.cats.effect.CatsResource
import org.specs2.matcher.MatcherImplicits.*
import org.specs2.mutable.SpecificationWithJUnit

class PriceListConsistencySpec
    extends SpecificationWithJUnit
    with CatsResource[TestResources] {

  override val resource: Resource[IO, TestResources] = ...

  "Test1" >> {
    "preview return non-empty successful response" >> { (tr: TestResources) =>
      "fail here" >> (true must beFalse)
      tr.fooStore
        .getFoo()
        .value
        .map(_ must beRight { (foo: Seq[Foo]) =>
          foo must not(beEmpty)
        })
    }
```

**Comment by armanbilge** [comment]
Thanks for opening the issue!

Your third example passes because `IO` is referentially transparent. That means the `IO(true).map(_ must beFalse)` is actually not executed at all, because it is in a statement position.

As for the first example, I don't think this is specific to specs2-cats or resources. Would you expect the following example to pass or fail? It only uses specs2-junit.

```scala
class PriceListConsistencySpec extends SpecificationWithJUnit {

  "Test1" >> {
    "preview return non-empty successful response" >> {
      "fail here" >> (true must beFalse)
      true must beTrue
    }
  }
}
```

I get
```
PriceListConsistencySpec
 
Test1
  + preview return non-empty successful response
 
 
Total for specification PriceListConsistencySpec
```

**Comment by etorreborre** [comment]
@unthingable this is a limitation of the DSL. Some expressions can be written but not evaluated as you would expect. When you are thinking about blocks in specs2 you need to think about "construction time". This is when you build your specification and declare that examples are nested. A nested structure like:
```
"Test1" >> {
    "preview return non-empty successful response" >> {
       "fail here" >> ...
     }
}
```
is more or less saying:
 - create an instruction to print a bit of text "Test1"
 - create an instruction to print as indented text "preview return non-empty successful response"
 - create an example which will return a Result when executed and with the description "fail"
 
 Any code that is executed as part of that sequence is not really "test code", it's "declaration code".

Once this is done, we enter the "execution time", the text is printed, and the examples are executed.

I hope that help you understand what's going on and I suppose that your specification should be written as:
```
 "Test1" >> {
    "preview return non-empty successful response" >> { (tr: TestResources) =>
      "fail here" >> { (tr: TestResources) => true must beFalse }
      "but hopefully not there" >> { (tr: TestResources) => 
           tr.fooStore
           .getFoo()
           .value
           .map(_ must beRight { (foo: Seq[Foo]) => foo must not(beEmpty)  })
       }
    }
 ```

**Comment by unthingable** [comment]
It's entirely possible I opened a non-issue then! My familiarity with specs2 is not extremely extensive, but yes, I would naively expect the test above (with three nested blocks) to pass.

Yes indeed the IO example is referentially transparent. I was trying it earlier via `IO(true) must beSuccess(_ must beTrue)` with the same result, got the two confused.

**Comment by unthingable** [comment]
> I hope that help you understand what's going on and I suppose that your specification should be written as

Thank you, it does though I'm still missing something because with the rewritten example I get an error along the lines of

```scala
no implicit argument of type MySpec.this.ToBlock[
  (MySpec.TestResources => 
    org.specs2.specification.core.Fragment
  )
, R] was found for parameter t of method >> in trait BlockDsl
where:    R is a type variable with constraint 
.
I found:
    this.given_ToBlock_R_Fragment[
      
        (MySpec.TestResources => 
          org.specs2.specification.core.Fragment
        )
      
    ](
      this.given_AsExecution_Function[org.specs2.specification.core.Fragment](
        org.specs2.specification.core.AsExecution.given_AsExecution_R[
          org.specs2.specification.core.Fragment
        ](
          org.specs2.execute.AsResult.asResult[
            org.specs2.specification.core.Fragment
          ](
            /* missing */
              summon[org.specs2.specification.core.Fragment => 
                org.specs2.execute.Result
              ]
          )
        )
      )
    )
But no implicit values were found that match type org.specs2.specification.core.Fragment => org.specs2.execute.Result
```

To specs2's credit, I've been able to take the inner workings for granted for a few years prior. Thank you for these explanations.

**Comment by etorreborre** [comment]
My fault. The rewritten example should be
```
 "Test1" >> {
    "preview return non-empty successful response" >> {  // no (tr: TestResources) here!
      "fail here" >> { (tr: TestResources) => true must beFalse }
      "but hopefully not there" >> { (tr: TestResources) => 
           tr.fooStore
           .getFoo()
           .value
           .map(_ must beRight { (foo: Seq[Foo]) => foo must not(beEmpty)  })
       }
    }
}
```
The `TestResources` can only be passed as parameters to the actual examples directly using them. I don't have a fully compiled project to prove it but I guess that this is the problem here.

**Comment by unthingable** [comment]
> The rewritten example should be
> 
> ```
>  "Test1" >> {
>     "preview return non-empty successful response" >> {  // no (tr: TestResources) here!
>       "fail here" >> { (tr: TestResources) => true must beFalse }
>       "but hopefully not there" >> { (tr: TestResources) => 
>            tr.fooStore
>            .getFoo()
>            .value
>            .map(_ must beRight { (foo: Seq[Foo]) => foo must not(beEmpty)  })
>        }
>     }
> }
> ```
> 
> The `TestResources` can only be passed as parameters to the actual examples directly using them. I don't have a fully compiled project to prove it but I guess that this is the problem here.

This compiles, thank you. So in other words, if I need additional tests on results obtained from passed resources, those cannot be in their own blocks.

**Comment by unthingable** [comment]
Turns out I've been holding it wrong and didn't RTFM enough: instead of using nested blocks to annotate nested tests, expectation descriptions do the job just fine.

**Comment by etorreborre** [comment]
> if I need additional tests on results obtained from passed resources, those cannot be in their own blocks.

If you feel adventurous you can try a feature called ["online specification"](https://etorreborre.github.io/specs2/guide/SPECS2-5.0.4/org.specs2.guide.CreateOnlineSpecifications.html). It is mostly designed to work with immutable specifications only but allows the creation of further examples based on the results of existing ones. 

For example you can write
```
import specification.*
import core.*

class OnlineSpec extends org.specs2.mutable.Specification with dsl.Online:
  "this is a test" >> {
    "first example" >> {
      val result = 1 + 1
      (result === 2).continueWith(moreExamples("a result"))

      // or, if the result is an `Execution` coming from an `IO` or a `Future` action
      //  val result = Execution.future(Future.successful(true))
      //result.setContinuation(moreExamples("a result"))

    }
  }

  // we need to use an immutable specification here
  def moreExamples(s: String) =
    s2"""
  some more examples
    second example $ok
    third example $ok
    """
```
This will display
```
[info] OnlineSpec
[info]
[info] this is a test
[info]   + first example
[info]     some more examples
[info]         + second example
[info]         + third example
[info]
```
